from telegram import Update
from telegram.ext import CallbackContext
from typing import Dict

def start(update: Update, context: CallbackContext) -> None:...
def echo(update: Update, context: CallbackContext) -> None:...
def analyze_history(update: Update, context: CallbackContext) -> None:...
def _unpack_telegram_document(update: Update) -> Dict:...