from telegram import Update
from telegram.ext import CallbackContext

def start(update: Update, context: CallbackContext) -> None:...
def help_info(update: Update, context: CallbackContext) -> None:...
def analyze_history(update: Update, context: CallbackContext) -> None:...
